name: Cache Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create folder for caching
        run: |
          mkdir -p test-cache
          echo "Hello world" > test-cache/file.txt

      - name: Cache folder
        id: cache-step
        uses: actions/cache@v4
        with:
          path: test-cache
          key: cache-241e4c2

      - name: Show cache hit/miss
        run: echo "Cache hit status: ${{ steps.cache-step.outputs.cache-hit }}"
